/**
 * Colour vocabulary shared across the engine and its consumers.
 *
 * CLASSIFIER_COLOR_WORDS is the classifier's own list (YOY-61): a colour
 * next to anything else makes a query constraint-shaped. It stays
 * deliberately small so an unlisted colour never blocks the classic fast
 * path, and it is not extended here — routing behaviour is pinned by the
 * eval goldens.
 *
 * COLORWAY_WORDS (YOY-117 AC-1) is the committed superset the product-family
 * rule reads: the classifier list plus the common colourway vocabulary of
 * fashion catalogues (shades, finishes, and the modifiers that precede a
 * colour — "dusty pink", "washed indigo", "meteorite black" is still a
 * colourway because its LAST word is a colour). A trailing title designator
 * (`in <Colour>`, `- <Colour>`, `/ <Colour>`, `(<Colour>)`) of one or two
 * words whose last word is in this set is a colourway, so "Rib Knit Top in
 * Pink" and "Rib Knit Top in Navy" are one family.
 */
export const CLASSIFIER_COLOR_WORDS: ReadonlySet<string> = new Set([
  "black",
  "white",
  "red",
  "blue",
  "green",
  "yellow",
  "pink",
  "purple",
  "orange",
  "brown",
  "grey",
  "gray",
  "beige",
  "gold",
  "silver",
  "navy",
  "שחור",
  "שחורה",
  "לבן",
  "לבנה",
  "אדום",
  "אדומה",
  "כחול",
  "כחולה",
  "ירוק",
  "ירוקה",
  "צהוב",
  "צהובה",
  "ורוד",
  "ורודה",
  "סגול",
  "סגולה",
  "כתום",
  "כתומה",
  "חום",
  "חומה",
  "אפור",
  "אפורה",
  "בז'",
  "זהב",
  "כסף",
]);

export const COLORWAY_WORDS: ReadonlySet<string> = new Set([
  ...CLASSIFIER_COLOR_WORDS,
  "ivory",
  "cream",
  "off-white",
  "ecru",
  "tan",
  "camel",
  "khaki",
  "olive",
  "sage",
  "teal",
  "turquoise",
  "aqua",
  "mint",
  "lime",
  "coral",
  "peach",
  "blush",
  "rose",
  "fuchsia",
  "magenta",
  "lavender",
  "lilac",
  "violet",
  "indigo",
  "cobalt",
  "burgundy",
  "maroon",
  "wine",
  "rust",
  "terracotta",
  "mustard",
  "charcoal",
  "graphite",
  "slate",
  "stone",
  "sand",
  "taupe",
  "nude",
  "chocolate",
  "espresso",
  "denim",
  "multi",
  "multicolour",
  "multicolor",
  "print",
  "floral",
  "striped",
  "bronze",
  "copper",
  "platinum",
  "pearl",
  "natural",
  "oat",
  "oatmeal",
  "forest",
  "emerald",
  "ruby",
  "sapphire",
  "plum",
  "berry",
  "cherry",
  "lemon",
  "mocha",
  "cognac",
  "mauve",
  "petrol",
  "bordeaux",
  "anthracite",
  "heather",
  "marl",
  "ochre",
  "saffron",
  "apricot",
  "tangerine",
  "scarlet",
  "crimson",
  "cyan",
  "royal",
  "light",
  "dark",
  "pale",
  "deep",
  "bright",
  "dusty",
  "soft",
  "washed",
  "vintage",
  "faded",
  "heathered",
  "mottled",
  "metallic",
  "matte",
  "glossy",
]);

/** Whether a word (lowercased, punctuation-trimmed) is a colourway word. */
export function isColorwayWord(word: string): boolean {
  return COLORWAY_WORDS.has(word.trim().toLowerCase());
}
